### ISSUE TITLE
Add YAML Support

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-provider-boilerplate#34]
The boilerplate repo does not support yaml out of the box. `GetSchema` GRPC method must return the actual schema.json contents for yaml to work. Good news is we've already done this in two repos (albeit slightly different approaches)

pulumi-pulumiservice: https://github.com/pulumi/pulumi-pulumiservice/issues/58
pulumi-command: https://github.com/pulumi/pulumi-command/issues/61

**Comment by guineveresaenger** [comment]
Fixed via #37
