### ISSUE TITLE
Indicate that this is a Github Template Repo in repo settings

### ISSUE THREAD

**Issue by charlex** [pulumi/pulumi-provider-boilerplate#5]
[How to](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

Why: 

> After you make your repository a template, anyone with access to the repository can generate a new repository with the same directory structure and files as your default branch. They can also choose to include all the other branches in your repository. For more information, see "Creating a repository from a template."

**Comment by stack72** [comment]
This has been updated to a template repository as requested :) Thanks for that!
