### ISSUE TITLE
Upgrade Pulumi and remove install-pulumi-plugin.js handling

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-provider-boilerplate#69]
### What happened?

For both native and bridged providers upgrading past
https://github.com/pulumi/pulumi/releases/tag/v3.80.0 introduces an important change (for bridged
providers this starting with
https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.59.0). The change is fully
described in https://github.com/pulumi/pulumi/pull/13800 and affects how Node and Python packages
are generated.

Prior to the change, installing the Node or Python version of a bridged provider via npm or pip
would run a script that ensures that the provider binary itself is installed. After the change, that
is no longer the case, and Pulumi CLI takes over the responsibility for automatic installation.

In practice you may observe files disapperaing upon upgrade, for example these files will be removed
from Pulumi bridged providers:

https://github.com/pulumi/pulumi-aws-apigateway/blob/main/sdk/nodejs/scripts/install-pulumi-plugin.js
https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/nodejs/scripts/install-pulumi-plugin.js

If your project is using Makefile targets that deal with these scripts, these require a small
update. For example, in pulumi-azure-native we need to remove the following line from the Makefile:

    mkdir -p bin/scripts && cp scripts/install-pulumi-plugin.js bin/scripts

### Expected Behavior

See above

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Scripts removed in https://github.com/pulumi/pulumi-provider-boilerplate/pull/71
